name: Manual Workflow
on:
  workflow_dispatch:

jobs:
  print_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        env:
          MY_NAME: ${{ secrets.MY_NAME }}
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_SECRET: ${{ secrets.MY_PORTFOLIO }}
        run: |
          echo "Name: $MY_NAME"
          echo "Email: $MY_EMAIL"
          echo "Secret: $MY_SECRET"
